# Generated by Django 3.2.7 on 2021-11-01 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicSearch', '0005_auto_20211011_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user_rated',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='avaliado', to='auth.user'),
            preserve_default=False,
        ),
    ]
